// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: execTxnRpc.proto

package execTxnRpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Online      bool              `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	TreeUuid    string            `protobuf:"bytes,2,opt,name=tree_uuid,json=treeUuid,proto3" json:"tree_uuid,omitempty"`
	ServiceUuid string            `protobuf:"bytes,3,opt,name=service_uuid,json=serviceUuid,proto3" json:"service_uuid,omitempty"`
	ParentUuid  string            `protobuf:"bytes,4,opt,name=parent_uuid,json=parentUuid,proto3" json:"parent_uuid,omitempty"`
	Children    []string          `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	DbName      string            `protobuf:"bytes,6,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	TableName   string            `protobuf:"bytes,7,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Method1     bool              `protobuf:"varint,8,opt,name=method1,proto3" json:"method1,omitempty"`
	Method2     bool              `protobuf:"varint,9,opt,name=method2,proto3" json:"method2,omitempty"`
	Query       string            `protobuf:"bytes,10,opt,name=query,proto3" json:"query,omitempty"` // 若query有多个值，则使用","分隔开。
	Data        map[string]string `protobuf:"bytes,11,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TxnMessage) Reset() {
	*x = TxnMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_execTxnRpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnMessage) ProtoMessage() {}

func (x *TxnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_execTxnRpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnMessage.ProtoReflect.Descriptor instead.
func (*TxnMessage) Descriptor() ([]byte, []int) {
	return file_execTxnRpc_proto_rawDescGZIP(), []int{0}
}

func (x *TxnMessage) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *TxnMessage) GetTreeUuid() string {
	if x != nil {
		return x.TreeUuid
	}
	return ""
}

func (x *TxnMessage) GetServiceUuid() string {
	if x != nil {
		return x.ServiceUuid
	}
	return ""
}

func (x *TxnMessage) GetParentUuid() string {
	if x != nil {
		return x.ParentUuid
	}
	return ""
}

func (x *TxnMessage) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *TxnMessage) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *TxnMessage) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TxnMessage) GetMethod1() bool {
	if x != nil {
		return x.Method1
	}
	return false
}

func (x *TxnMessage) GetMethod2() bool {
	if x != nil {
		return x.Method2
	}
	return false
}

func (x *TxnMessage) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TxnMessage) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type TxnStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TxnStatus) Reset() {
	*x = TxnStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_execTxnRpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnStatus) ProtoMessage() {}

func (x *TxnStatus) ProtoReflect() protoreflect.Message {
	mi := &file_execTxnRpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnStatus.ProtoReflect.Descriptor instead.
func (*TxnStatus) Descriptor() ([]byte, []int) {
	return file_execTxnRpc_proto_rawDescGZIP(), []int{1}
}

func (x *TxnStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TxnStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_execTxnRpc_proto protoreflect.FileDescriptor

var file_execTxnRpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x78, 0x65, 0x63, 0x54, 0x78, 0x6e, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x87, 0x03, 0x0a, 0x0a, 0x54, 0x78, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x65,
	0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72,
	0x65, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x31, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x32, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x54, 0x78, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3d, 0x0a, 0x09,
	0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x30, 0x0a, 0x0a, 0x45,
	0x78, 0x65, 0x63, 0x54, 0x78, 0x6e, 0x52, 0x70, 0x63, 0x12, 0x22, 0x0a, 0x07, 0x65, 0x78, 0x65,
	0x63, 0x54, 0x78, 0x6e, 0x12, 0x0b, 0x2e, 0x54, 0x78, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x0a, 0x2e, 0x54, 0x78, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x54, 0x78, 0x6e, 0x52, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_execTxnRpc_proto_rawDescOnce sync.Once
	file_execTxnRpc_proto_rawDescData = file_execTxnRpc_proto_rawDesc
)

func file_execTxnRpc_proto_rawDescGZIP() []byte {
	file_execTxnRpc_proto_rawDescOnce.Do(func() {
		file_execTxnRpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_execTxnRpc_proto_rawDescData)
	})
	return file_execTxnRpc_proto_rawDescData
}

var file_execTxnRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_execTxnRpc_proto_goTypes = []interface{}{
	(*TxnMessage)(nil), // 0: TxnMessage
	(*TxnStatus)(nil),  // 1: TxnStatus
	nil,                // 2: TxnMessage.DataEntry
}
var file_execTxnRpc_proto_depIdxs = []int32{
	2, // 0: TxnMessage.data:type_name -> TxnMessage.DataEntry
	0, // 1: ExecTxnRpc.execTxn:input_type -> TxnMessage
	1, // 2: ExecTxnRpc.execTxn:output_type -> TxnStatus
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_execTxnRpc_proto_init() }
func file_execTxnRpc_proto_init() {
	if File_execTxnRpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_execTxnRpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_execTxnRpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_execTxnRpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execTxnRpc_proto_goTypes,
		DependencyIndexes: file_execTxnRpc_proto_depIdxs,
		MessageInfos:      file_execTxnRpc_proto_msgTypes,
	}.Build()
	File_execTxnRpc_proto = out.File
	file_execTxnRpc_proto_rawDesc = nil
	file_execTxnRpc_proto_goTypes = nil
	file_execTxnRpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ExecTxnRpcClient is the client API for ExecTxnRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExecTxnRpcClient interface {
	ExecTxn(ctx context.Context, in *TxnMessage, opts ...grpc.CallOption) (*TxnStatus, error)
}

type execTxnRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewExecTxnRpcClient(cc grpc.ClientConnInterface) ExecTxnRpcClient {
	return &execTxnRpcClient{cc}
}

func (c *execTxnRpcClient) ExecTxn(ctx context.Context, in *TxnMessage, opts ...grpc.CallOption) (*TxnStatus, error) {
	out := new(TxnStatus)
	err := c.cc.Invoke(ctx, "/ExecTxnRpc/execTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecTxnRpcServer is the server API for ExecTxnRpc service.
type ExecTxnRpcServer interface {
	ExecTxn(context.Context, *TxnMessage) (*TxnStatus, error)
}

// UnimplementedExecTxnRpcServer can be embedded to have forward compatible implementations.
type UnimplementedExecTxnRpcServer struct {
}

func (*UnimplementedExecTxnRpcServer) ExecTxn(context.Context, *TxnMessage) (*TxnStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecTxn not implemented")
}

func RegisterExecTxnRpcServer(s *grpc.Server, srv ExecTxnRpcServer) {
	s.RegisterService(&_ExecTxnRpc_serviceDesc, srv)
}

func _ExecTxnRpc_ExecTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecTxnRpcServer).ExecTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExecTxnRpc/ExecTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecTxnRpcServer).ExecTxn(ctx, req.(*TxnMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExecTxnRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExecTxnRpc",
	HandlerType: (*ExecTxnRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "execTxn",
			Handler:    _ExecTxnRpc_ExecTxn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "execTxnRpc.proto",
}
