package edu.bridge.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commonInfo.proto

public final class CommonInfoOuterClass {
  private CommonInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HttpRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HttpRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool online = 1;</code>
     */
    boolean getOnline();

    /**
     * <code>uint32 pos = 2;</code>
     */
    int getPos();

    /**
     * <code>string tree_uuid = 3;</code>
     */
    String getTreeUuid();
    /**
     * <code>string tree_uuid = 3;</code>
     */
    com.google.protobuf.ByteString
        getTreeUuidBytes();

    /**
     * <code>string service_uuid = 4;</code>
     */
    String getServiceUuid();
    /**
     * <code>string service_uuid = 4;</code>
     */
    com.google.protobuf.ByteString
        getServiceUuidBytes();

    /**
     * <code>uint32 mapper_num = 5;</code>
     */
    int getMapperNum();

    /**
     * <code>uint32 service_num = 6;</code>
     */
    int getServiceNum();

    /**
     * <code>string db_name = 7;</code>
     */
    String getDbName();
    /**
     * <code>string db_name = 7;</code>
     */
    com.google.protobuf.ByteString
        getDbNameBytes();

    /**
     * <code>string table_name = 8;</code>
     */
    String getTableName();
    /**
     * <code>string table_name = 8;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <code>bool method1 = 9;</code>
     */
    boolean getMethod1();

    /**
     * <code>bool method2 = 10;</code>
     */
    boolean getMethod2();

    /**
     * <code>string query = 11;</code>
     */
    String getQuery();
    /**
     * <code>string query = 11;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */
    int getDataCount();
    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */
    boolean containsData(
            String key);
    /**
     * Use {@link #getDataMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getData();
    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */
    java.util.Map<String, String>
    getDataMap();
    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */

    String getDataOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */

    String getDataOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code HttpRequest}
   */
  public  static final class HttpRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HttpRequest)
      HttpRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HttpRequest.newBuilder() to construct.
    private HttpRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HttpRequest() {
      online_ = false;
      pos_ = 0;
      treeUuid_ = "";
      serviceUuid_ = "";
      mapperNum_ = 0;
      serviceNum_ = 0;
      dbName_ = "";
      tableName_ = "";
      method1_ = false;
      method2_ = false;
      query_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HttpRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              online_ = input.readBool();
              break;
            }
            case 16: {

              pos_ = input.readUInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              treeUuid_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              serviceUuid_ = s;
              break;
            }
            case 40: {

              mapperNum_ = input.readUInt32();
              break;
            }
            case 48: {

              serviceNum_ = input.readUInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              dbName_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            case 72: {

              method1_ = input.readBool();
              break;
            }
            case 80: {

              method2_ = input.readBool();
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            case 98: {
              if (!((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
                data_ = com.google.protobuf.MapField.newMapField(
                    DataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000800;
              }
              com.google.protobuf.MapEntry<String, String>
              data__ = input.readMessage(
                  DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              data_.getMutableMap().put(
                  data__.getKey(), data__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonInfoOuterClass.internal_static_HttpRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 12:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonInfoOuterClass.internal_static_HttpRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HttpRequest.class, Builder.class);
    }

    private int bitField0_;
    public static final int ONLINE_FIELD_NUMBER = 1;
    private boolean online_;
    /**
     * <code>bool online = 1;</code>
     */
    public boolean getOnline() {
      return online_;
    }

    public static final int POS_FIELD_NUMBER = 2;
    private int pos_;
    /**
     * <code>uint32 pos = 2;</code>
     */
    public int getPos() {
      return pos_;
    }

    public static final int TREE_UUID_FIELD_NUMBER = 3;
    private volatile Object treeUuid_;
    /**
     * <code>string tree_uuid = 3;</code>
     */
    public String getTreeUuid() {
      Object ref = treeUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        treeUuid_ = s;
        return s;
      }
    }
    /**
     * <code>string tree_uuid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTreeUuidBytes() {
      Object ref = treeUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        treeUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_UUID_FIELD_NUMBER = 4;
    private volatile Object serviceUuid_;
    /**
     * <code>string service_uuid = 4;</code>
     */
    public String getServiceUuid() {
      Object ref = serviceUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serviceUuid_ = s;
        return s;
      }
    }
    /**
     * <code>string service_uuid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServiceUuidBytes() {
      Object ref = serviceUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAPPER_NUM_FIELD_NUMBER = 5;
    private int mapperNum_;
    /**
     * <code>uint32 mapper_num = 5;</code>
     */
    public int getMapperNum() {
      return mapperNum_;
    }

    public static final int SERVICE_NUM_FIELD_NUMBER = 6;
    private int serviceNum_;
    /**
     * <code>uint32 service_num = 6;</code>
     */
    public int getServiceNum() {
      return serviceNum_;
    }

    public static final int DB_NAME_FIELD_NUMBER = 7;
    private volatile Object dbName_;
    /**
     * <code>string db_name = 7;</code>
     */
    public String getDbName() {
      Object ref = dbName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dbName_ = s;
        return s;
      }
    }
    /**
     * <code>string db_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDbNameBytes() {
      Object ref = dbName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLE_NAME_FIELD_NUMBER = 8;
    private volatile Object tableName_;
    /**
     * <code>string table_name = 8;</code>
     */
    public String getTableName() {
      Object ref = tableName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <code>string table_name = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD1_FIELD_NUMBER = 9;
    private boolean method1_;
    /**
     * <code>bool method1 = 9;</code>
     */
    public boolean getMethod1() {
      return method1_;
    }

    public static final int METHOD2_FIELD_NUMBER = 10;
    private boolean method2_;
    /**
     * <code>bool method2 = 10;</code>
     */
    public boolean getMethod2() {
      return method2_;
    }

    public static final int QUERY_FIELD_NUMBER = 11;
    private volatile Object query_;
    /**
     * <code>string query = 11;</code>
     */
    public String getQuery() {
      Object ref = query_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <code>string query = 11;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 12;
    private static final class DataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  CommonInfoOuterClass.internal_static_HttpRequest_DataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> data_;
    private com.google.protobuf.MapField<String, String>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }

    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */

    public boolean containsData(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */

    public java.util.Map<String, String> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */

    public String getDataOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; data = 12;</code>
     */

    public String getDataOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (online_ != false) {
        output.writeBool(1, online_);
      }
      if (pos_ != 0) {
        output.writeUInt32(2, pos_);
      }
      if (!getTreeUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, treeUuid_);
      }
      if (!getServiceUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serviceUuid_);
      }
      if (mapperNum_ != 0) {
        output.writeUInt32(5, mapperNum_);
      }
      if (serviceNum_ != 0) {
        output.writeUInt32(6, serviceNum_);
      }
      if (!getDbNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, dbName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tableName_);
      }
      if (method1_ != false) {
        output.writeBool(9, method1_);
      }
      if (method2_ != false) {
        output.writeBool(10, method2_);
      }
      if (!getQueryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, query_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetData(),
          DataDefaultEntryHolder.defaultEntry,
          12);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (online_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, online_);
      }
      if (pos_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, pos_);
      }
      if (!getTreeUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, treeUuid_);
      }
      if (!getServiceUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serviceUuid_);
      }
      if (mapperNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, mapperNum_);
      }
      if (serviceNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, serviceNum_);
      }
      if (!getDbNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, dbName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tableName_);
      }
      if (method1_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, method1_);
      }
      if (method2_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, method2_);
      }
      if (!getQueryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, query_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(12, data__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HttpRequest)) {
        return super.equals(obj);
      }
      HttpRequest other = (HttpRequest) obj;

      boolean result = true;
      result = result && (getOnline()
          == other.getOnline());
      result = result && (getPos()
          == other.getPos());
      result = result && getTreeUuid()
          .equals(other.getTreeUuid());
      result = result && getServiceUuid()
          .equals(other.getServiceUuid());
      result = result && (getMapperNum()
          == other.getMapperNum());
      result = result && (getServiceNum()
          == other.getServiceNum());
      result = result && getDbName()
          .equals(other.getDbName());
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && (getMethod1()
          == other.getMethod1());
      result = result && (getMethod2()
          == other.getMethod2());
      result = result && getQuery()
          .equals(other.getQuery());
      result = result && internalGetData().equals(
          other.internalGetData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ONLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOnline());
      hash = (37 * hash) + POS_FIELD_NUMBER;
      hash = (53 * hash) + getPos();
      hash = (37 * hash) + TREE_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getTreeUuid().hashCode();
      hash = (37 * hash) + SERVICE_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getServiceUuid().hashCode();
      hash = (37 * hash) + MAPPER_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getMapperNum();
      hash = (37 * hash) + SERVICE_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getServiceNum();
      hash = (37 * hash) + DB_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDbName().hashCode();
      hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (37 * hash) + METHOD1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMethod1());
      hash = (37 * hash) + METHOD2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMethod2());
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      if (!internalGetData().getMap().isEmpty()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HttpRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HttpRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HttpRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HttpRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HttpRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HttpRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HttpRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HttpRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HttpRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HttpRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HttpRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HttpRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HttpRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HttpRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HttpRequest)
        HttpRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonInfoOuterClass.internal_static_HttpRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 12:
            return internalGetData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 12:
            return internalGetMutableData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonInfoOuterClass.internal_static_HttpRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HttpRequest.class, Builder.class);
      }

      // Construct using CommonInfoOuterClass.HttpRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        online_ = false;

        pos_ = 0;

        treeUuid_ = "";

        serviceUuid_ = "";

        mapperNum_ = 0;

        serviceNum_ = 0;

        dbName_ = "";

        tableName_ = "";

        method1_ = false;

        method2_ = false;

        query_ = "";

        internalGetMutableData().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonInfoOuterClass.internal_static_HttpRequest_descriptor;
      }

      public HttpRequest getDefaultInstanceForType() {
        return HttpRequest.getDefaultInstance();
      }

      public HttpRequest build() {
        HttpRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HttpRequest buildPartial() {
        HttpRequest result = new HttpRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.online_ = online_;
        result.pos_ = pos_;
        result.treeUuid_ = treeUuid_;
        result.serviceUuid_ = serviceUuid_;
        result.mapperNum_ = mapperNum_;
        result.serviceNum_ = serviceNum_;
        result.dbName_ = dbName_;
        result.tableName_ = tableName_;
        result.method1_ = method1_;
        result.method2_ = method2_;
        result.query_ = query_;
        result.data_ = internalGetData();
        result.data_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HttpRequest) {
          return mergeFrom((HttpRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HttpRequest other) {
        if (other == HttpRequest.getDefaultInstance()) return this;
        if (other.getOnline() != false) {
          setOnline(other.getOnline());
        }
        if (other.getPos() != 0) {
          setPos(other.getPos());
        }
        if (!other.getTreeUuid().isEmpty()) {
          treeUuid_ = other.treeUuid_;
          onChanged();
        }
        if (!other.getServiceUuid().isEmpty()) {
          serviceUuid_ = other.serviceUuid_;
          onChanged();
        }
        if (other.getMapperNum() != 0) {
          setMapperNum(other.getMapperNum());
        }
        if (other.getServiceNum() != 0) {
          setServiceNum(other.getServiceNum());
        }
        if (!other.getDbName().isEmpty()) {
          dbName_ = other.dbName_;
          onChanged();
        }
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        if (other.getMethod1() != false) {
          setMethod1(other.getMethod1());
        }
        if (other.getMethod2() != false) {
          setMethod2(other.getMethod2());
        }
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        internalGetMutableData().mergeFrom(
            other.internalGetData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HttpRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HttpRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean online_ ;
      /**
       * <code>bool online = 1;</code>
       */
      public boolean getOnline() {
        return online_;
      }
      /**
       * <code>bool online = 1;</code>
       */
      public Builder setOnline(boolean value) {
        
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool online = 1;</code>
       */
      public Builder clearOnline() {
        
        online_ = false;
        onChanged();
        return this;
      }

      private int pos_ ;
      /**
       * <code>uint32 pos = 2;</code>
       */
      public int getPos() {
        return pos_;
      }
      /**
       * <code>uint32 pos = 2;</code>
       */
      public Builder setPos(int value) {
        
        pos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 pos = 2;</code>
       */
      public Builder clearPos() {
        
        pos_ = 0;
        onChanged();
        return this;
      }

      private Object treeUuid_ = "";
      /**
       * <code>string tree_uuid = 3;</code>
       */
      public String getTreeUuid() {
        Object ref = treeUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          treeUuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tree_uuid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTreeUuidBytes() {
        Object ref = treeUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          treeUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tree_uuid = 3;</code>
       */
      public Builder setTreeUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        treeUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tree_uuid = 3;</code>
       */
      public Builder clearTreeUuid() {
        
        treeUuid_ = getDefaultInstance().getTreeUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string tree_uuid = 3;</code>
       */
      public Builder setTreeUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        treeUuid_ = value;
        onChanged();
        return this;
      }

      private Object serviceUuid_ = "";
      /**
       * <code>string service_uuid = 4;</code>
       */
      public String getServiceUuid() {
        Object ref = serviceUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serviceUuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string service_uuid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getServiceUuidBytes() {
        Object ref = serviceUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string service_uuid = 4;</code>
       */
      public Builder setServiceUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string service_uuid = 4;</code>
       */
      public Builder clearServiceUuid() {
        
        serviceUuid_ = getDefaultInstance().getServiceUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string service_uuid = 4;</code>
       */
      public Builder setServiceUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceUuid_ = value;
        onChanged();
        return this;
      }

      private int mapperNum_ ;
      /**
       * <code>uint32 mapper_num = 5;</code>
       */
      public int getMapperNum() {
        return mapperNum_;
      }
      /**
       * <code>uint32 mapper_num = 5;</code>
       */
      public Builder setMapperNum(int value) {
        
        mapperNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 mapper_num = 5;</code>
       */
      public Builder clearMapperNum() {
        
        mapperNum_ = 0;
        onChanged();
        return this;
      }

      private int serviceNum_ ;
      /**
       * <code>uint32 service_num = 6;</code>
       */
      public int getServiceNum() {
        return serviceNum_;
      }
      /**
       * <code>uint32 service_num = 6;</code>
       */
      public Builder setServiceNum(int value) {
        
        serviceNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 service_num = 6;</code>
       */
      public Builder clearServiceNum() {
        
        serviceNum_ = 0;
        onChanged();
        return this;
      }

      private Object dbName_ = "";
      /**
       * <code>string db_name = 7;</code>
       */
      public String getDbName() {
        Object ref = dbName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dbName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string db_name = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDbNameBytes() {
        Object ref = dbName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dbName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string db_name = 7;</code>
       */
      public Builder setDbName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dbName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string db_name = 7;</code>
       */
      public Builder clearDbName() {
        
        dbName_ = getDefaultInstance().getDbName();
        onChanged();
        return this;
      }
      /**
       * <code>string db_name = 7;</code>
       */
      public Builder setDbNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dbName_ = value;
        onChanged();
        return this;
      }

      private Object tableName_ = "";
      /**
       * <code>string table_name = 8;</code>
       */
      public String getTableName() {
        Object ref = tableName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string table_name = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string table_name = 8;</code>
       */
      public Builder setTableName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string table_name = 8;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>string table_name = 8;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }

      private boolean method1_ ;
      /**
       * <code>bool method1 = 9;</code>
       */
      public boolean getMethod1() {
        return method1_;
      }
      /**
       * <code>bool method1 = 9;</code>
       */
      public Builder setMethod1(boolean value) {
        
        method1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool method1 = 9;</code>
       */
      public Builder clearMethod1() {
        
        method1_ = false;
        onChanged();
        return this;
      }

      private boolean method2_ ;
      /**
       * <code>bool method2 = 10;</code>
       */
      public boolean getMethod2() {
        return method2_;
      }
      /**
       * <code>bool method2 = 10;</code>
       */
      public Builder setMethod2(boolean value) {
        
        method2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool method2 = 10;</code>
       */
      public Builder clearMethod2() {
        
        method2_ = false;
        onChanged();
        return this;
      }

      private Object query_ = "";
      /**
       * <code>string query = 11;</code>
       */
      public String getQuery() {
        Object ref = query_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string query = 11;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string query = 11;</code>
       */
      public Builder setQuery(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string query = 11;</code>
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <code>string query = 11;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> data_;
      private com.google.protobuf.MapField<String, String>
      internalGetData() {
        if (data_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        return data_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableData() {
        onChanged();;
        if (data_ == null) {
          data_ = com.google.protobuf.MapField.newMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        if (!data_.isMutable()) {
          data_ = data_.copy();
        }
        return data_;
      }

      public int getDataCount() {
        return internalGetData().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; data = 12;</code>
       */

      public boolean containsData(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDataMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getData() {
        return getDataMap();
      }
      /**
       * <code>map&lt;string, string&gt; data = 12;</code>
       */

      public java.util.Map<String, String> getDataMap() {
        return internalGetData().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; data = 12;</code>
       */

      public String getDataOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; data = 12;</code>
       */

      public String getDataOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetData().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearData() {
        internalGetMutableData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; data = 12;</code>
       */

      public Builder removeData(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableData() {
        return internalGetMutableData().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; data = 12;</code>
       */
      public Builder putData(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; data = 12;</code>
       */

      public Builder putAllData(
          java.util.Map<String, String> values) {
        internalGetMutableData().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HttpRequest)
    }

    // @@protoc_insertion_point(class_scope:HttpRequest)
    private static final HttpRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HttpRequest();
    }

    public static HttpRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HttpRequest>
        PARSER = new com.google.protobuf.AbstractParser<HttpRequest>() {
      public HttpRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HttpRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HttpRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HttpRequest> getParserForType() {
      return PARSER;
    }

    public HttpRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HttpResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HttpResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code HttpResponse}
   */
  public  static final class HttpResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HttpResponse)
      HttpResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HttpResponse.newBuilder() to construct.
    private HttpResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HttpResponse() {
      success_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HttpResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonInfoOuterClass.internal_static_HttpResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonInfoOuterClass.internal_static_HttpResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HttpResponse.class, Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HttpResponse)) {
        return super.equals(obj);
      }
      HttpResponse other = (HttpResponse) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HttpResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HttpResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HttpResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HttpResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HttpResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HttpResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HttpResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HttpResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HttpResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HttpResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HttpResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HttpResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HttpResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HttpResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HttpResponse)
        HttpResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonInfoOuterClass.internal_static_HttpResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonInfoOuterClass.internal_static_HttpResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HttpResponse.class, Builder.class);
      }

      // Construct using CommonInfoOuterClass.HttpResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonInfoOuterClass.internal_static_HttpResponse_descriptor;
      }

      public HttpResponse getDefaultInstanceForType() {
        return HttpResponse.getDefaultInstance();
      }

      public HttpResponse build() {
        HttpResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HttpResponse buildPartial() {
        HttpResponse result = new HttpResponse(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HttpResponse) {
          return mergeFrom((HttpResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HttpResponse other) {
        if (other == HttpResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HttpResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HttpResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HttpResponse)
    }

    // @@protoc_insertion_point(class_scope:HttpResponse)
    private static final HttpResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HttpResponse();
    }

    public static HttpResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HttpResponse>
        PARSER = new com.google.protobuf.AbstractParser<HttpResponse>() {
      public HttpResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HttpResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HttpResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HttpResponse> getParserForType() {
      return PARSER;
    }

    public HttpResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HttpRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HttpRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HttpRequest_DataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HttpRequest_DataEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HttpResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HttpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020commonInfo.proto\"\245\002\n\013HttpRequest\022\016\n\006on" +
      "line\030\001 \001(\010\022\013\n\003pos\030\002 \001(\r\022\021\n\ttree_uuid\030\003 \001" +
      "(\t\022\024\n\014service_uuid\030\004 \001(\t\022\022\n\nmapper_num\030\005" +
      " \001(\r\022\023\n\013service_num\030\006 \001(\r\022\017\n\007db_name\030\007 \001" +
      "(\t\022\022\n\ntable_name\030\010 \001(\t\022\017\n\007method1\030\t \001(\010\022" +
      "\017\n\007method2\030\n \001(\010\022\r\n\005query\030\013 \001(\t\022$\n\004data\030" +
      "\014 \003(\0132\026.HttpRequest.DataEntry\032+\n\tDataEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\037\n\014Ht" +
      "tpResponse\022\017\n\007success\030\001 \001(\0102=\n\nCommonInf" +
      "o\022/\n\020sendToDataCenter\022\014.HttpRequest\032\r.Ht" +
      "tpResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HttpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HttpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HttpRequest_descriptor,
        new String[] { "Online", "Pos", "TreeUuid", "ServiceUuid", "MapperNum", "ServiceNum", "DbName", "TableName", "Method1", "Method2", "Query", "Data", });
    internal_static_HttpRequest_DataEntry_descriptor =
      internal_static_HttpRequest_descriptor.getNestedTypes().get(0);
    internal_static_HttpRequest_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HttpRequest_DataEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_HttpResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HttpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HttpResponse_descriptor,
        new String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
