server:
  port: 8888
spring:
  application:
    name: payment-service
  cloud:
    nacos:
      discovery:
        server-addr: my.aliyun.com:8848
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://my.aliyun.com:3306/test_payment
#    username: root
#    password: password
feign:
  hystrix:
    enabled: false
  # feign调用超时时间配置
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
gRPC:
  host: 127.0.0.1
  port: 1996