server:
  port: 8888
spring:
  application:
    name: payment-service
  cloud:
    nacos:
      discovery:
        server-addr: my.aliyun.com:1111
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://my.aliyun.com:3306/test_payment
#    username: root
#    password: password
feign:
  hystrix:
    enabled: false
gRPC:
  host: 127.0.0.1
  port: 1996