server:
  port: 9999
spring:
  application:
    name: storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.201.121.145:1111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.201.121.145:3306/test_storage
    username: root
    password: Bupt_Bridge_Wang
feign:
  hystrix:
    enabled: false
gRPC:
  host: 127.0.0.1
  port: 1996