package edu.bridge.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: execTxnRpc.proto

public final class ExecTxnRpcOuterClass {
  private ExecTxnRpcOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TxnMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TxnMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool online = 1;</code>
     */
    boolean getOnline();

    /**
     * <code>string tree_uuid = 2;</code>
     */
    String getTreeUuid();
    /**
     * <code>string tree_uuid = 2;</code>
     */
    com.google.protobuf.ByteString
        getTreeUuidBytes();

    /**
     * <code>string service_uuid = 3;</code>
     */
    String getServiceUuid();
    /**
     * <code>string service_uuid = 3;</code>
     */
    com.google.protobuf.ByteString
        getServiceUuidBytes();

    /**
     * <code>string parent_uuid = 4;</code>
     */
    String getParentUuid();
    /**
     * <code>string parent_uuid = 4;</code>
     */
    com.google.protobuf.ByteString
        getParentUuidBytes();

    /**
     * <code>repeated string children = 5;</code>
     */
    java.util.List<String>
        getChildrenList();
    /**
     * <code>repeated string children = 5;</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated string children = 5;</code>
     */
    String getChildren(int index);
    /**
     * <code>repeated string children = 5;</code>
     */
    com.google.protobuf.ByteString
        getChildrenBytes(int index);

    /**
     * <code>string db_name = 6;</code>
     */
    String getDbName();
    /**
     * <code>string db_name = 6;</code>
     */
    com.google.protobuf.ByteString
        getDbNameBytes();

    /**
     * <code>string table_name = 7;</code>
     */
    String getTableName();
    /**
     * <code>string table_name = 7;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <code>bool method1 = 8;</code>
     */
    boolean getMethod1();

    /**
     * <code>bool method2 = 9;</code>
     */
    boolean getMethod2();

    /**
     * <pre>
     * 若query有多个值，则使用","分隔开。
     * </pre>
     *
     * <code>string query = 10;</code>
     */
    String getQuery();
    /**
     * <pre>
     * 若query有多个值，则使用","分隔开。
     * </pre>
     *
     * <code>string query = 10;</code>
     */
    com.google.protobuf.ByteString
        getQueryBytes();

    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */
    int getDataCount();
    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */
    boolean containsData(
            String key);
    /**
     * Use {@link #getDataMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getData();
    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */
    java.util.Map<String, String>
    getDataMap();
    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */

    String getDataOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */

    String getDataOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code TxnMessage}
   */
  public  static final class TxnMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TxnMessage)
      TxnMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxnMessage.newBuilder() to construct.
    private TxnMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxnMessage() {
      online_ = false;
      treeUuid_ = "";
      serviceUuid_ = "";
      parentUuid_ = "";
      children_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      dbName_ = "";
      tableName_ = "";
      method1_ = false;
      method2_ = false;
      query_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxnMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              online_ = input.readBool();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              treeUuid_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              serviceUuid_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              parentUuid_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                children_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              children_.add(s);
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              dbName_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            case 64: {

              method1_ = input.readBool();
              break;
            }
            case 72: {

              method2_ = input.readBool();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              query_ = s;
              break;
            }
            case 90: {
              if (!((mutable_bitField0_ & 0x00000400) == 0x00000400)) {
                data_ = com.google.protobuf.MapField.newMapField(
                    DataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000400;
              }
              com.google.protobuf.MapEntry<String, String>
              data__ = input.readMessage(
                  DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              data_.getMutableMap().put(
                  data__.getKey(), data__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          children_ = children_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExecTxnRpcOuterClass.internal_static_TxnMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 11:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExecTxnRpcOuterClass.internal_static_TxnMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TxnMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int ONLINE_FIELD_NUMBER = 1;
    private boolean online_;
    /**
     * <code>bool online = 1;</code>
     */
    public boolean getOnline() {
      return online_;
    }

    public static final int TREE_UUID_FIELD_NUMBER = 2;
    private volatile Object treeUuid_;
    /**
     * <code>string tree_uuid = 2;</code>
     */
    public String getTreeUuid() {
      Object ref = treeUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        treeUuid_ = s;
        return s;
      }
    }
    /**
     * <code>string tree_uuid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTreeUuidBytes() {
      Object ref = treeUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        treeUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_UUID_FIELD_NUMBER = 3;
    private volatile Object serviceUuid_;
    /**
     * <code>string service_uuid = 3;</code>
     */
    public String getServiceUuid() {
      Object ref = serviceUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serviceUuid_ = s;
        return s;
      }
    }
    /**
     * <code>string service_uuid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getServiceUuidBytes() {
      Object ref = serviceUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARENT_UUID_FIELD_NUMBER = 4;
    private volatile Object parentUuid_;
    /**
     * <code>string parent_uuid = 4;</code>
     */
    public String getParentUuid() {
      Object ref = parentUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        parentUuid_ = s;
        return s;
      }
    }
    /**
     * <code>string parent_uuid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getParentUuidBytes() {
      Object ref = parentUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        parentUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHILDREN_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList children_;
    /**
     * <code>repeated string children = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated string children = 5;</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated string children = 5;</code>
     */
    public String getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated string children = 5;</code>
     */
    public com.google.protobuf.ByteString
        getChildrenBytes(int index) {
      return children_.getByteString(index);
    }

    public static final int DB_NAME_FIELD_NUMBER = 6;
    private volatile Object dbName_;
    /**
     * <code>string db_name = 6;</code>
     */
    public String getDbName() {
      Object ref = dbName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dbName_ = s;
        return s;
      }
    }
    /**
     * <code>string db_name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDbNameBytes() {
      Object ref = dbName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dbName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TABLE_NAME_FIELD_NUMBER = 7;
    private volatile Object tableName_;
    /**
     * <code>string table_name = 7;</code>
     */
    public String getTableName() {
      Object ref = tableName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <code>string table_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD1_FIELD_NUMBER = 8;
    private boolean method1_;
    /**
     * <code>bool method1 = 8;</code>
     */
    public boolean getMethod1() {
      return method1_;
    }

    public static final int METHOD2_FIELD_NUMBER = 9;
    private boolean method2_;
    /**
     * <code>bool method2 = 9;</code>
     */
    public boolean getMethod2() {
      return method2_;
    }

    public static final int QUERY_FIELD_NUMBER = 10;
    private volatile Object query_;
    /**
     * <pre>
     * 若query有多个值，则使用","分隔开。
     * </pre>
     *
     * <code>string query = 10;</code>
     */
    public String getQuery() {
      Object ref = query_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        query_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 若query有多个值，则使用","分隔开。
     * </pre>
     *
     * <code>string query = 10;</code>
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 11;
    private static final class DataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  ExecTxnRpcOuterClass.internal_static_TxnMessage_DataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> data_;
    private com.google.protobuf.MapField<String, String>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }

    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */

    public boolean containsData(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */

    public java.util.Map<String, String> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */

    public String getDataOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; data = 11;</code>
     */

    public String getDataOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (online_ != false) {
        output.writeBool(1, online_);
      }
      if (!getTreeUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, treeUuid_);
      }
      if (!getServiceUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, serviceUuid_);
      }
      if (!getParentUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parentUuid_);
      }
      for (int i = 0; i < children_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, children_.getRaw(i));
      }
      if (!getDbNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dbName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, tableName_);
      }
      if (method1_ != false) {
        output.writeBool(8, method1_);
      }
      if (method2_ != false) {
        output.writeBool(9, method2_);
      }
      if (!getQueryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, query_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetData(),
          DataDefaultEntryHolder.defaultEntry,
          11);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (online_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, online_);
      }
      if (!getTreeUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, treeUuid_);
      }
      if (!getServiceUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, serviceUuid_);
      }
      if (!getParentUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parentUuid_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < children_.size(); i++) {
          dataSize += computeStringSizeNoTag(children_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getChildrenList().size();
      }
      if (!getDbNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dbName_);
      }
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, tableName_);
      }
      if (method1_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, method1_);
      }
      if (method2_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, method2_);
      }
      if (!getQueryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, query_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(11, data__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TxnMessage)) {
        return super.equals(obj);
      }
      TxnMessage other = (TxnMessage) obj;

      boolean result = true;
      result = result && (getOnline()
          == other.getOnline());
      result = result && getTreeUuid()
          .equals(other.getTreeUuid());
      result = result && getServiceUuid()
          .equals(other.getServiceUuid());
      result = result && getParentUuid()
          .equals(other.getParentUuid());
      result = result && getChildrenList()
          .equals(other.getChildrenList());
      result = result && getDbName()
          .equals(other.getDbName());
      result = result && getTableName()
          .equals(other.getTableName());
      result = result && (getMethod1()
          == other.getMethod1());
      result = result && (getMethod2()
          == other.getMethod2());
      result = result && getQuery()
          .equals(other.getQuery());
      result = result && internalGetData().equals(
          other.internalGetData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ONLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOnline());
      hash = (37 * hash) + TREE_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getTreeUuid().hashCode();
      hash = (37 * hash) + SERVICE_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getServiceUuid().hashCode();
      hash = (37 * hash) + PARENT_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getParentUuid().hashCode();
      if (getChildrenCount() > 0) {
        hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
        hash = (53 * hash) + getChildrenList().hashCode();
      }
      hash = (37 * hash) + DB_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getDbName().hashCode();
      hash = (37 * hash) + TABLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (37 * hash) + METHOD1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMethod1());
      hash = (37 * hash) + METHOD2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMethod2());
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
      if (!internalGetData().getMap().isEmpty()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TxnMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxnMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxnMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TxnMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxnMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxnMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TxnMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TxnMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TxnMessage)
        TxnMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExecTxnRpcOuterClass.internal_static_TxnMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 11:
            return internalGetData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 11:
            return internalGetMutableData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExecTxnRpcOuterClass.internal_static_TxnMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TxnMessage.class, Builder.class);
      }

      // Construct using ExecTxnRpcOuterClass.TxnMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        online_ = false;

        treeUuid_ = "";

        serviceUuid_ = "";

        parentUuid_ = "";

        children_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        dbName_ = "";

        tableName_ = "";

        method1_ = false;

        method2_ = false;

        query_ = "";

        internalGetMutableData().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExecTxnRpcOuterClass.internal_static_TxnMessage_descriptor;
      }

      public TxnMessage getDefaultInstanceForType() {
        return TxnMessage.getDefaultInstance();
      }

      public TxnMessage build() {
        TxnMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TxnMessage buildPartial() {
        TxnMessage result = new TxnMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.online_ = online_;
        result.treeUuid_ = treeUuid_;
        result.serviceUuid_ = serviceUuid_;
        result.parentUuid_ = parentUuid_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          children_ = children_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.children_ = children_;
        result.dbName_ = dbName_;
        result.tableName_ = tableName_;
        result.method1_ = method1_;
        result.method2_ = method2_;
        result.query_ = query_;
        result.data_ = internalGetData();
        result.data_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TxnMessage) {
          return mergeFrom((TxnMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TxnMessage other) {
        if (other == TxnMessage.getDefaultInstance()) return this;
        if (other.getOnline() != false) {
          setOnline(other.getOnline());
        }
        if (!other.getTreeUuid().isEmpty()) {
          treeUuid_ = other.treeUuid_;
          onChanged();
        }
        if (!other.getServiceUuid().isEmpty()) {
          serviceUuid_ = other.serviceUuid_;
          onChanged();
        }
        if (!other.getParentUuid().isEmpty()) {
          parentUuid_ = other.parentUuid_;
          onChanged();
        }
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
        if (!other.getDbName().isEmpty()) {
          dbName_ = other.dbName_;
          onChanged();
        }
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        if (other.getMethod1() != false) {
          setMethod1(other.getMethod1());
        }
        if (other.getMethod2() != false) {
          setMethod2(other.getMethod2());
        }
        if (!other.getQuery().isEmpty()) {
          query_ = other.query_;
          onChanged();
        }
        internalGetMutableData().mergeFrom(
            other.internalGetData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TxnMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TxnMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean online_ ;
      /**
       * <code>bool online = 1;</code>
       */
      public boolean getOnline() {
        return online_;
      }
      /**
       * <code>bool online = 1;</code>
       */
      public Builder setOnline(boolean value) {
        
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool online = 1;</code>
       */
      public Builder clearOnline() {
        
        online_ = false;
        onChanged();
        return this;
      }

      private Object treeUuid_ = "";
      /**
       * <code>string tree_uuid = 2;</code>
       */
      public String getTreeUuid() {
        Object ref = treeUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          treeUuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tree_uuid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTreeUuidBytes() {
        Object ref = treeUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          treeUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tree_uuid = 2;</code>
       */
      public Builder setTreeUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        treeUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tree_uuid = 2;</code>
       */
      public Builder clearTreeUuid() {
        
        treeUuid_ = getDefaultInstance().getTreeUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string tree_uuid = 2;</code>
       */
      public Builder setTreeUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        treeUuid_ = value;
        onChanged();
        return this;
      }

      private Object serviceUuid_ = "";
      /**
       * <code>string service_uuid = 3;</code>
       */
      public String getServiceUuid() {
        Object ref = serviceUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serviceUuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string service_uuid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getServiceUuidBytes() {
        Object ref = serviceUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string service_uuid = 3;</code>
       */
      public Builder setServiceUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serviceUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string service_uuid = 3;</code>
       */
      public Builder clearServiceUuid() {
        
        serviceUuid_ = getDefaultInstance().getServiceUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string service_uuid = 3;</code>
       */
      public Builder setServiceUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serviceUuid_ = value;
        onChanged();
        return this;
      }

      private Object parentUuid_ = "";
      /**
       * <code>string parent_uuid = 4;</code>
       */
      public String getParentUuid() {
        Object ref = parentUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          parentUuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string parent_uuid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getParentUuidBytes() {
        Object ref = parentUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          parentUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string parent_uuid = 4;</code>
       */
      public Builder setParentUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parentUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string parent_uuid = 4;</code>
       */
      public Builder clearParentUuid() {
        
        parentUuid_ = getDefaultInstance().getParentUuid();
        onChanged();
        return this;
      }
      /**
       * <code>string parent_uuid = 4;</code>
       */
      public Builder setParentUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        parentUuid_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList children_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          children_ = new com.google.protobuf.LazyStringArrayList(children_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getChildrenList() {
        return children_.getUnmodifiableView();
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public int getChildrenCount() {
        return children_.size();
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public String getChildren(int index) {
        return children_.get(index);
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public com.google.protobuf.ByteString
          getChildrenBytes(int index) {
        return children_.getByteString(index);
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public Builder setChildren(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public Builder addChildren(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public Builder addAllChildren(
          Iterable<String> values) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public Builder clearChildren() {
        children_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string children = 5;</code>
       */
      public Builder addChildrenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
        return this;
      }

      private Object dbName_ = "";
      /**
       * <code>string db_name = 6;</code>
       */
      public String getDbName() {
        Object ref = dbName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dbName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string db_name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDbNameBytes() {
        Object ref = dbName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dbName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string db_name = 6;</code>
       */
      public Builder setDbName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dbName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string db_name = 6;</code>
       */
      public Builder clearDbName() {
        
        dbName_ = getDefaultInstance().getDbName();
        onChanged();
        return this;
      }
      /**
       * <code>string db_name = 6;</code>
       */
      public Builder setDbNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dbName_ = value;
        onChanged();
        return this;
      }

      private Object tableName_ = "";
      /**
       * <code>string table_name = 7;</code>
       */
      public String getTableName() {
        Object ref = tableName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string table_name = 7;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string table_name = 7;</code>
       */
      public Builder setTableName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string table_name = 7;</code>
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>string table_name = 7;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }

      private boolean method1_ ;
      /**
       * <code>bool method1 = 8;</code>
       */
      public boolean getMethod1() {
        return method1_;
      }
      /**
       * <code>bool method1 = 8;</code>
       */
      public Builder setMethod1(boolean value) {
        
        method1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool method1 = 8;</code>
       */
      public Builder clearMethod1() {
        
        method1_ = false;
        onChanged();
        return this;
      }

      private boolean method2_ ;
      /**
       * <code>bool method2 = 9;</code>
       */
      public boolean getMethod2() {
        return method2_;
      }
      /**
       * <code>bool method2 = 9;</code>
       */
      public Builder setMethod2(boolean value) {
        
        method2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool method2 = 9;</code>
       */
      public Builder clearMethod2() {
        
        method2_ = false;
        onChanged();
        return this;
      }

      private Object query_ = "";
      /**
       * <pre>
       * 若query有多个值，则使用","分隔开。
       * </pre>
       *
       * <code>string query = 10;</code>
       */
      public String getQuery() {
        Object ref = query_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          query_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 若query有多个值，则使用","分隔开。
       * </pre>
       *
       * <code>string query = 10;</code>
       */
      public com.google.protobuf.ByteString
          getQueryBytes() {
        Object ref = query_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          query_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 若query有多个值，则使用","分隔开。
       * </pre>
       *
       * <code>string query = 10;</code>
       */
      public Builder setQuery(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 若query有多个值，则使用","分隔开。
       * </pre>
       *
       * <code>string query = 10;</code>
       */
      public Builder clearQuery() {
        
        query_ = getDefaultInstance().getQuery();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 若query有多个值，则使用","分隔开。
       * </pre>
       *
       * <code>string query = 10;</code>
       */
      public Builder setQueryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        query_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> data_;
      private com.google.protobuf.MapField<String, String>
      internalGetData() {
        if (data_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        return data_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableData() {
        onChanged();;
        if (data_ == null) {
          data_ = com.google.protobuf.MapField.newMapField(
              DataDefaultEntryHolder.defaultEntry);
        }
        if (!data_.isMutable()) {
          data_ = data_.copy();
        }
        return data_;
      }

      public int getDataCount() {
        return internalGetData().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; data = 11;</code>
       */

      public boolean containsData(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getDataMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getData() {
        return getDataMap();
      }
      /**
       * <code>map&lt;string, string&gt; data = 11;</code>
       */

      public java.util.Map<String, String> getDataMap() {
        return internalGetData().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; data = 11;</code>
       */

      public String getDataOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; data = 11;</code>
       */

      public String getDataOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetData().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearData() {
        internalGetMutableData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; data = 11;</code>
       */

      public Builder removeData(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableData() {
        return internalGetMutableData().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; data = 11;</code>
       */
      public Builder putData(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; data = 11;</code>
       */

      public Builder putAllData(
          java.util.Map<String, String> values) {
        internalGetMutableData().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TxnMessage)
    }

    // @@protoc_insertion_point(class_scope:TxnMessage)
    private static final TxnMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TxnMessage();
    }

    public static TxnMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxnMessage>
        PARSER = new com.google.protobuf.AbstractParser<TxnMessage>() {
      public TxnMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxnMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxnMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TxnMessage> getParserForType() {
      return PARSER;
    }

    public TxnMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxnStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TxnStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <code>string message = 2;</code>
     */
    String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code TxnStatus}
   */
  public  static final class TxnStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TxnStatus)
      TxnStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxnStatus.newBuilder() to construct.
    private TxnStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxnStatus() {
      status_ = 0;
      message_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxnStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExecTxnRpcOuterClass.internal_static_TxnStatus_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExecTxnRpcOuterClass.internal_static_TxnStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TxnStatus.class, Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TxnStatus)) {
        return super.equals(obj);
      }
      TxnStatus other = (TxnStatus) obj;

      boolean result = true;
      result = result && (getStatus()
          == other.getStatus());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TxnStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TxnStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TxnStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxnStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxnStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TxnStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TxnStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TxnStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TxnStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TxnStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TxnStatus)
        TxnStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExecTxnRpcOuterClass.internal_static_TxnStatus_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExecTxnRpcOuterClass.internal_static_TxnStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TxnStatus.class, Builder.class);
      }

      // Construct using ExecTxnRpcOuterClass.TxnStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExecTxnRpcOuterClass.internal_static_TxnStatus_descriptor;
      }

      public TxnStatus getDefaultInstanceForType() {
        return TxnStatus.getDefaultInstance();
      }

      public TxnStatus build() {
        TxnStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TxnStatus buildPartial() {
        TxnStatus result = new TxnStatus(this);
        result.status_ = status_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TxnStatus) {
          return mergeFrom((TxnStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TxnStatus other) {
        if (other == TxnStatus.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TxnStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TxnStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TxnStatus)
    }

    // @@protoc_insertion_point(class_scope:TxnStatus)
    private static final TxnStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TxnStatus();
    }

    public static TxnStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxnStatus>
        PARSER = new com.google.protobuf.AbstractParser<TxnStatus>() {
      public TxnStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxnStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxnStatus> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TxnStatus> getParserForType() {
      return PARSER;
    }

    public TxnStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TxnMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TxnMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TxnMessage_DataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TxnMessage_DataEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TxnStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TxnStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020execTxnRpc.proto\"\224\002\n\nTxnMessage\022\016\n\006onl" +
      "ine\030\001 \001(\010\022\021\n\ttree_uuid\030\002 \001(\t\022\024\n\014service_" +
      "uuid\030\003 \001(\t\022\023\n\013parent_uuid\030\004 \001(\t\022\020\n\010child" +
      "ren\030\005 \003(\t\022\017\n\007db_name\030\006 \001(\t\022\022\n\ntable_name" +
      "\030\007 \001(\t\022\017\n\007method1\030\010 \001(\010\022\017\n\007method2\030\t \001(\010" +
      "\022\r\n\005query\030\n \001(\t\022#\n\004data\030\013 \003(\0132\025.TxnMessa" +
      "ge.DataEntry\032+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\t:\0028\001\",\n\tTxnStatus\022\016\n\006status" +
      "\030\001 \001(\005\022\017\n\007message\030\002 \001(\t20\n\nExecTxnRpc\022\"\n" +
      "\007execTxn\022\013.TxnMessage\032\n.TxnStatusB\016Z\014./e" +
      "xecTxnRpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TxnMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TxnMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TxnMessage_descriptor,
        new String[] { "Online", "TreeUuid", "ServiceUuid", "ParentUuid", "Children", "DbName", "TableName", "Method1", "Method2", "Query", "Data", });
    internal_static_TxnMessage_DataEntry_descriptor =
      internal_static_TxnMessage_descriptor.getNestedTypes().get(0);
    internal_static_TxnMessage_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TxnMessage_DataEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_TxnStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TxnStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TxnStatus_descriptor,
        new String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
