server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        # 自定义事务组的名字要与seata-server中的config一致
        tx-service-group: msvc_txn_mgmt_seata
    nacos:
      discovery:
        server-addr: my.aliyun.com:1111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://my.aliyun.com:3306/seata_order
    username: root
    password: Bupt_Bridge_Wang
feign:
  hystrix:
    enabled: false
  # feign调用超时时间配置
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000

logging:
  level:
    io:
      seata: info
mybatis:
  mapperLocations: classpath:mapper/*.xml