server:
  port: 7777
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.201.121.145:1111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.201.121.145:3306/seata_order
    username: root
    password: Bupt_Bridge_Wang
feign:
  hystrix:
    enabled: false
gRPC:
  host: 127.0.0.1
  port: 1996