app:
  port: 52100
  timelapses: 50
cluster:
  enabled: true
  reg_center: "127.0.0.1:1996"
  health_check_time: 30
  memory: 4096  #MB
database:
  driver: "mysql"
  database_names:
#    - "tx_register"
#    - "tx_profile"
#    - "tx_user_info"
  enable_slave_database: false
  max_idle_connection: 16
  max_open_connection: 100
  main:
    url: "127.0.0.1:3306"
    user: "root"
    password: "123456"
  slaves:
    urls:
      - "127.0.0.1:3306"
      - "10.112.175.91:3306"
      - "10.112.221.144:3306"
      - "10.112.217.236:3306"
    users:
      - "root"
      - "root"
      - "root"
      - "root"
    passwords:
      - "123456"
      - "root123456"
      - "123456"
      - "123456"