app:
  port: 1996
  timelapses: 50

database:
  driver: "mysql"
  database_names:
    - "test_order"
    - "test_storage"
    - "test_payment"
  enable_slave_database: false
  max_idle_connection: 16
  max_open_connection: 100
  main:
    url: "127.0.0.1:3306"
    user: "root"
    password: "root123456"
  slaves:
    urls:
      - "10.112.221.144:3306"
      - "10.112.217.236:3306"
    users:
      - "root"
      - "root"
    passwords:
      - "123456"
      - "123456"